
services:
  postgres:
    build: .
    container_name: employees_db_uzb
    environment:
      - POSTGRES_USER=root1
      - POSTGRES_PASSWORD=root1
      - POSTGRES_DB=employees
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - uzb_network

networks:
  uzb_network: 
    driver: bridge